a=int(input("enter a a:"))
b=int(input("enter a b(breadth):"))
h=int(input("enter a h(height):"))
r=int(input("enter a r(radius):"))
area1=(1/2*b*h)
area2=(3.14*r*r)
area3=(a*a)
print("area of triangle is",area1)
print("area of circle is",area2)
print("area of square is",area3)
