a=int(input("enter a number a:"))
b=int(input("enter a number b:"))
sum=(a+b)
sub=(a-b)
multi=(a*b)
divide=(a/b)
print("addition :",sum)
print("subtraction:",sub)
print("multiplication:",multi)
print("division:",divide)
